version: '3.8'

services:

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file: .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"


  minio-mc:
    image: minio/mc:latest
    depends_on: [ minio ]
    env_file: .env
    entrypoint: >
      sh -c "
      sleep 5 &&
      mc config host add local http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} &&
      mc mb local/${MINIO_BUCKET} || true &&
      mc anonymous set download local/${MINIO_BUCKET} &&
      mc ilm add --expiry-days 1 local/${MINIO_BUCKET}
      "


  mongodb:
    image: mongo:latest
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"




volumes:
  minio-data:
  mongodb-data:
